### ISSUE TITLE
Fork repo in 360Learning

### ISSUE THREAD

**Issue by FabriceGaudin** [hugoattal/hugoattal.github.io#3]
Hey @hugoattal cc @TheHerobrine

Do you see any problem if I fork this repo in the 360Learning team? This way we'll be able to do future changes without bothering you :blush: 

Hope you're doing well! :sunglasses:

**Comment by hugoattal360** [comment]
@FabriceGaudin Yes of course, no problem 😉 ! I'm merging the Ed's PR btw 🙂

**Comment by FabriceGaudin** [comment]
@hugoattal Thanks a lot! :pray:  Done :)

**Comment by FabriceGaudin** [comment]
@hugoattal Actually by using a fork, the github page is hosted on something like https://360learning.github.io/hugoattal.github.io/ :sweat_smile: 
Do you agree transfering ownership of this repo through the settings (Settings tab > Transfer ownership)?
Thanks again and sorry for the trouble!

**Comment by hugoattal** [comment]
@FabriceGaudin Actually, you may want to copy the repository and make it "360learning.github.io", so that the adress will be https://360learning.github.io, wdyt 🤔 ?

**Comment by FabriceGaudin** [comment]
@TheHerobrine Indeed, it was that easy :facepalm: 
Thanks!
